name: Build SecurAI
on:
  workflow_dispatch:
  push:
    paths:
      - 'BackEnd/**'
      - 'FrontEnd/**'
      - 'main.js'
      - 'package.json'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Inicialización de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
        

      - name: Instalación de dependencias de Python
        run: pip install -r BackEnd/requirements.txt

      - name: Caché del build del Backend con PyInstaller
        id: cache-pyinstaller
        uses: actions/cache@v4
        with:
          path: |
            BackEnd/build
            BackEnd/dist
          key: ${{ runner.os }}-pyinstaller-${{ hashFiles('BackEnd/run.spec', 'BackEnd/**.py') }}
      

      - name: Build del BackEnd con pyinstaller
        if: steps.cache-pyinstaller.outputs.cache-hit != 'true'
        run: |
            cd BackEnd
            pyinstaller --noconfirm run.spec
            cd /dist
            cp -R run/_internal/* .
            rm -rf run

      - name: Reorganizar carpeta dist
        run: |
          cd BackEnd/dist
          # Copiar todos los archivos de dist/run/_internal a dist/
          cp -R run/_internal/* .
          # Borrar la carpeta dist/run completamente
          rm -rf run
        shell: bash
    
      - name: Inicialización de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'
    
      - name: Caché de dependencias de Node
        id: cache-node
        uses: actions/cache@v4
        with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-
        
      - name: Instalación de dependencias de Node
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install
        

      - name: Build de la app completa
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            npx electron-builder --mac --x64 --publish always
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npx electron-builder --win --publish always
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
