name: Build SecurAI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testRelease
      - macARM
      - pruebaMacos-latest
    paths:
      - 'BackEnd/**'
      - 'FrontEnd/**'
      - 'main.js'
      - 'package.json'
      - '.github/workflows/*.yaml'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
            variant: x86
          - os: macos-15
            variant: arm64
          - os: windows-latest
            variant: x86
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Inicialización de Python
      - name: Inicialización de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # Instalar dependencias del BackEnd
      - name: Instalación de dependencias de Python
        run: |
          pip install -r BackEnd/requirements.txt
        shell: bash

      - name: Reemplazar TensorFlow por tensorflow-macos (macOS_ARM)
        run: |
          echo "RUNNER_OS=$RUNNER_OS"
          echo "VARIANT=$VARIANT"

          if [[ "$RUNNER_OS" == "macOS" && "$VARIANT" == "arm64" ]]; then
            echo "Entorno macOS ARM detectado. Reemplazando TensorFlow..."
            pip uninstall -y tensorflow || true
            pip install tensorflow-macos
          else
            echo "No es macOS ARM. No se reemplaza TensorFlow."
          fi
        shell: bash
        env:
          VARIANT: ${{ matrix.variant }}

      # Build del BackEnd
      - name: Caché del build del Backend con PyInstaller
        id: cache-pyinstaller
        uses: actions/cache@v4
        with:
          path: |
            BackEnd/build
            BackEnd/dist
          key: ${{ runner.os }}-${{ matrix.variant }}-pyinstaller-${{ hashFiles('BackEnd/run.spec', 'BackEnd/**.py') }}

      - name: Build del BackEnd con pyinstaller
        if: steps.cache-pyinstaller.outputs.cache-hit != 'true'
        run: |
          cd BackEnd
          pyinstaller --noconfirm run.spec
          cd dist
          cp -R run/_internal/* .
          rm -rf run
        shell: bash

      # Inicialización de Node.js
      - name: Inicialización de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'

      # Instalar dependencias del FrontEnd
      - name: Instalación de dependencias del FrontEnd
        run: |
          cd FrontEnd/app
              npm install --verbose

      # Build del FrontEnd
      - name: Caché de la build del FrontEnd
        id: cache-next-build
        uses: actions/cache@v4
        with:
          path: FrontEnd/app/.next
          key: ${{ runner.os }}-${{ matrix.variant }}-next-build-${{ hashFiles('FrontEnd/app/package.json', 'FrontEnd/app/package-lock.json', 'FrontEnd/app/**.js') }}

      - name: Build del Frontend
        if: steps.cache-next-build.outputs.cache-hit != 'true'
        run: |
          cd FrontEnd/app
          npm run build

      # Instalar dependencias de Electron
      - name: Instalación de dependencias de Electron
        run: |
          npm install

      # Build de la app completa
      - name: Caché de la build completa de Electron
        id: cache-electron-build
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-${{ matrix.variant }}-electron-build-${{ hashFiles('package.json', 'package-lock.json', 'main.js', 'dist/latest.yml', 'latest-mac.yml') }}

      - name: Build de la app completa
        if: steps.cache-electron-build.outputs.cache-hit != 'true'
        run: |
          if [[ "$RUNNER_OS" == "macOS" && "${{ matrix.variant }}" == "x86" ]]; then
            npx electron-builder --mac --x64
          elif [[ "$RUNNER_OS" == "macOS" && "${{ matrix.variant }}" == "arm64" ]]; then
            npx electron-builder --mac --arm64
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npx electron-builder --win --x64
          fi
        shell: bash

      - name: Leer versión desde package.json
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Subir artefactos de prueba
        if: github.ref_name != 'main'
        uses: actions/upload-artifact@v4
        with:
          name: SecurAI-${{ runner.os }}-${{ matrix.variant }}
          path: |
            dist/*.dmg
            dist/*.exe

      - name: Renombrar instaladores para release
        if: github.ref_name == 'main'
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            for f in dist/*.exe; do
              mv "$f" "dist/SecurAI-${{ runner.os }}-${{ matrix.variant }}.exe"
            done
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            for f in dist/*.dmg; do
              mv "$f" "dist/SecurAI-${{ runner.os }}-${{ matrix.variant }}.dmg"
            done
          fi
        shell: bash

      - name: Crear release
        if: github.ref_name == 'main'
        uses: softprops/action-gh-release@v1
        with:
          name: SecurAI v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          files: |
            dist/*.dmg
            dist/*.exe
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}