name: Build SecurAI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'BackEnd/**'
      - 'FrontEnd/**'
      - 'main.js'
      - 'package.json'
      - '.github/workflows/*.yaml'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Inicialización de Python
      - name: Inicialización de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # Instalar dependencias del BackEnd
      - name: Instalación de dependencias de Python
        run: pip install -r BackEnd/requirements.txt


      # Build del BackEnd
      - name: Caché del build del Backend con PyInstaller
        id: cache-pyinstaller
        uses: actions/cache@v4
        with:
          path: |
            BackEnd/build
            BackEnd/dist
          key: ${{ runner.os }}-pyinstaller-${{ hashFiles('BackEnd/run.spec', 'BackEnd/**.py') }}

      - name: Build del BackEnd con pyinstaller
        if: steps.cache-pyinstaller.outputs.cache-hit != 'true'
        run: |
          cd BackEnd
          pyinstaller --noconfirm run.spec
          cd dist
          cp -R run/_internal/* .
          rm -rf run
        shell: bash

      # Inicialización de Node.js
      - name: Inicialización de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'

      # Instalar dependencias del FrontEnd
      - name: Instalación de dependencias del FrontEnd
        run: |
          cd FrontEnd/app
          npm install

      # Build del FrontEnd
      - name: Caché de la build del FrontEnd
        id: cache-next-build
        uses: actions/cache@v4
        with:
          path: FrontEnd/app/.next  # Ruta de la carpeta .next
          key: ${{ runner.os }}-next-build-${{ hashFiles('FrontEnd/app/package.json', 'FrontEnd/app/package-lock.json') }}
          restore-keys: ${{ runner.os }}-next-build-

      - name: Build del Frontend
        if: steps.cache-next-build.outputs.cache-hit != 'true'  # Solo si no se ha encontrado la caché
        run: |
          cd FrontEnd/app
          npm run build
      
      # Instalar dependencias de Electron
      - name: Instalación de dependencias de Electron
        run: |
          npm install

      # Build de la app completa
      - name: Caché de la build completa de Electron
        id: cache-electron-build
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-electron-build-${{ hashFiles('package.json', 'package-lock.json', 'electron-builder.yml') }}
          restore-keys: ${{ runner.os }}-electron-build-

      - name: Build de la app completa
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            npx electron-builder --mac --x64 --publish always
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npx electron-builder --win --x64 --publish always
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.cache-electron-build.outputs.cache-hit != 'true'  # Solo construir si no se encuentra la caché

